name: Shell Checks

on:
  pull_request:
    paths:
      - "**.sh"

jobs:
  test:
    name: shellcheck
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Run shellcheck
        run: |
          shellcheck --version
          shellcheck -x *.sh
